# Generated by Django 2.2.1 on 2019-05-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190513_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
