# Generated by Django 2.2.1 on 2019-05-18 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_thread_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='updated_at',
        ),
    ]
