# Generated by Django 2.2.1 on 2019-05-20 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_thread_updated_at'),
    ]

    operations = [
    ]
