# Generated by Django 2.2.1 on 2019-05-10 03:05

import accounts.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10, null=True, verbose_name='gender')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='DOB')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10, null=True, verbose_name='blood group')),
                ('contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='contact')),
                ('address', models.TextField(blank=True, max_length=200, null=True, verbose_name='address')),
                ('about', models.TextField(blank=True, max_length=300, null=True, verbose_name='about')),
                ('facebook', models.CharField(blank=True, max_length=300, null=True, verbose_name='facebook')),
                ('linkedin', models.CharField(blank=True, max_length=300, null=True, verbose_name='linkedin')),
                ('website', models.CharField(blank=True, max_length=300, null=True, verbose_name='website')),
                ('image', models.ImageField(blank=True, null=True, upload_to=accounts.utils.upload_image_path, verbose_name='image')),
                ('account_type', models.PositiveSmallIntegerField(choices=[(0, 'Regular'), (1, 'Premium')], default=0, verbose_name='account type')),
                ('is_volunteer', models.BooleanField(default=False, verbose_name='is volunteer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-user__date_joined'],
            },
        ),
    ]
