# Generated by Django 2.2.1 on 2019-08-23 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_volunteer',
        ),
    ]
