# Generated by Django 2.2.1 on 2019-05-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190510_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='DOB'),
        ),
    ]
