# Generated by Django 2.2.1 on 2019-10-06 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_remove_userprofile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('category', models.CharField(choices=[('Inappropriate Behavior', 'Inappropriate Behavior'), ('Have Diseases', 'Have Diseases'), ('Asks for Money', 'Asks for Money'), ('Is not Authentic', 'Is not Authentic'), ('Others', 'Others')], max_length=100, verbose_name='category')),
                ('details', models.TextField(blank=True, null=True, verbose_name='details')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Report',
                'verbose_name_plural': 'User Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
