# Generated by Django 2.2.1 on 2019-05-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190512_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='contact'),
        ),
    ]
