# Generated by Django 2.2.1 on 2019-10-11 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191011_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_attachments', to='blog.Blog', verbose_name='blog'),
        ),
    ]
