# Generated by Django 2.2.1 on 2019-10-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191011_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='tags'),
        ),
    ]
