# Generated by Django 2.2.1 on 2019-10-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191020_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('article', 'Article'), ('story', 'Personal Story'), ('help', 'Help Post'), ('question', 'Questionnaire'), ('research', 'Research Activity'), ('issue', 'Issue'), ('other', 'Other')], default='Article', max_length=250, verbose_name='category'),
        ),
    ]
