# Generated by Django 2.2.1 on 2019-08-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='created_at',
            field=models.DateTimeField(verbose_name='created at'),
        ),
    ]
