# Generated by Django 2.2.1 on 2019-11-08 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'ordering': ['-created_at'], 'verbose_name': 'Checkout', 'verbose_name_plural': 'Checkouts'},
        ),
    ]
