# Generated by Django 2.2.1 on 2019-08-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='plan title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='amount')),
                ('currency', models.CharField(choices=[('USD', 'usd')], default='usd', max_length=50, verbose_name='currency')),
                ('expiration_cycle', models.PositiveSmallIntegerField(choices=[(1, '1 Month'), (2, '2 Month'), (3, '3 Month'), (4, '4 Month'), (5, '5 Month'), (6, '6 Month'), (7, '7 Month'), (8, '8 Month'), (9, '9 Month'), (10, '10 Month'), (11, '11 Month'), (12, '12 Month')], default=1, verbose_name='expiration cycle')),
                ('description', models.TextField(blank=True, max_length=100, null=True, verbose_name='short description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
