# Generated by Django 2.2.1 on 2019-08-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='expiration_cycle',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Month'), (2, '2 Month'), (3, '3 Month'), (4, '4 month'), (5, '5 month'), (6, '6 month'), (7, '7 month'), (8, '8 month'), (9, '9 month'), (10, '10 month'), (11, '11 month'), (12, '12 month')], default=1, verbose_name='expiration cycle'),
        ),
    ]
