# Generated by Django 2.2.1 on 2019-08-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceplan', '0002_auto_20190802_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='expiration_cycle',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Month'), (2, '2 Month'), (3, '3 Month'), (4, '4 Month'), (5, '5 Month'), (6, '6 Month'), (7, '7 Month'), (8, '8 Month'), (9, '9 Month'), (10, '10 Month'), (11, '11 Month'), (12, '12 Month')], default=1, verbose_name='expiration cycle'),
        ),
    ]
