# Generated by Django 2.2.1 on 2019-08-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceplan', '0004_auto_20190803_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.CharField(default='0', max_length=250, verbose_name='amount'),
        ),
    ]
