# Generated by Django 2.2.1 on 2019-08-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceplan', '0005_auto_20190803_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='amount'),
        ),
    ]
