# Generated by Django 2.2.1 on 2019-08-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceplan', '0006_auto_20190803_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='amount'),
        ),
    ]
