# Generated by Django 2.2.1 on 2019-08-02 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='post title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Offer Donation'), (1, 'Ask for Donation')], verbose_name='category')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Blood'), (1, 'Organ'), (2, 'Tissue')], verbose_name='donation type')),
                ('blood_group', models.CharField(blank=True, choices=[('Any Blood Group', 'Any Blood Group'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=20, null=True, verbose_name='blood group')),
                ('blood_bag', models.CharField(blank=True, max_length=4, null=True, verbose_name='blood bag quantity')),
                ('organ_name', models.CharField(blank=True, choices=[('Heart', 'Heart'), ('Kidney', 'Kidney'), ('Pancreas', 'Pancreas'), ('Lungs', 'Lungs'), ('Liver', 'Liver'), ('Intestines', 'Intestines')], max_length=100, null=True, verbose_name='organ name')),
                ('tissue_name', models.CharField(blank=True, choices=[('Bones', 'Bones'), ('Ligaments', 'Ligaments'), ('Tendons', 'Tendons'), ('Fascia', 'Fascia'), ('Veins', 'Veins'), ('Nerves', 'Nerves'), ('Corneas', 'Corneas'), ('Sclera', 'Sclera'), ('Heart Valves', 'Heart Valves'), ('Skin', 'Skin')], max_length=100, null=True, verbose_name='tissue name')),
                ('quantity', models.CharField(blank=True, max_length=4, null=True, verbose_name='quantity')),
                ('donate_type', models.PositiveSmallIntegerField(choices=[(0, 'Living'), (1, 'Deceased')], default=0, verbose_name='donate type')),
                ('is_verified', models.BooleanField(default=True, verbose_name='is verified')),
                ('details', models.TextField(blank=True, null=True, verbose_name='details')),
                ('contact', models.CharField(max_length=17, verbose_name='contact number')),
                ('contact2', models.CharField(blank=True, max_length=17, null=True, verbose_name='contact number 2')),
                ('contact3', models.CharField(blank=True, max_length=17, null=True, verbose_name='contact number 3')),
                ('contact_privacy', models.PositiveSmallIntegerField(choices=[(0, 'Public'), (1, 'Private')], default=0, verbose_name='contact privacy')),
                ('location', models.CharField(max_length=200, verbose_name='location')),
                ('hospital', models.CharField(blank=True, max_length=200, null=True, verbose_name='hospital')),
                ('preferred_date', models.DateTimeField(blank=True, null=True, verbose_name='preferred date')),
                ('preferred_date_from', models.DateTimeField(blank=True, null=True, verbose_name='preferred date from')),
                ('preferred_date_to', models.DateTimeField(blank=True, null=True, verbose_name='preferred date to')),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, 'Normal'), (1, 'Important')], default=0, verbose_name='priority')),
                ('publication_status', models.PositiveSmallIntegerField(choices=[(0, 'Published'), (1, 'Unpublished')], default=0, verbose_name='publication status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_profile', to='accounts.UserProfile', verbose_name='user')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationUtil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_util', to='donations.Donation', verbose_name='donation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_util_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Donation Util',
                'verbose_name_plural': 'Donation Utils',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationRespond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=17, null=True, verbose_name='contact')),
                ('message', models.TextField(blank=True, max_length=500, null=True, verbose_name='message')),
                ('is_selected', models.BooleanField(default=False, verbose_name='is selected')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_respond', to='donations.Donation', verbose_name='donation')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_respondent', to=settings.AUTH_USER_MODEL, verbose_name='respondent')),
            ],
            options={
                'verbose_name': 'Donation Respond',
                'verbose_name_plural': 'Donation Responds',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Completed')], default=0, verbose_name='progress status')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='completion date')),
                ('management_status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Managed on site'), (1, 'Managed on somewhere else')], null=True, verbose_name='managed on')),
                ('details', models.TextField(blank=True, max_length=500, null=True, verbose_name='details')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donation_progress', to='donations.Donation', verbose_name='donation')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_progress_respondent', to=settings.AUTH_USER_MODEL, verbose_name='respondent')),
            ],
            options={
                'verbose_name': 'Donation Progress',
                'verbose_name_plural': 'Donation Progresses',
                'ordering': ['-updated_at'],
            },
        ),
    ]
