# Generated by Django 2.2.1 on 2019-05-23 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_auto_20190512_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('category', models.CharField(choices=[('offer', 'Offer Donation'), ('ask', 'Ask for Donation')], max_length=50, verbose_name='category')),
                ('type', models.CharField(choices=[('Blood', 'Male'), ('Body Organs', 'Female'), ('Others', 'Others')], max_length=30, verbose_name='type')),
                ('custom_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='custom type')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10, null=True, verbose_name='blood group')),
                ('organ_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='organ name')),
                ('details', models.TextField(blank=True, max_length=500, null=True, verbose_name='details')),
                ('preferred_date', models.DateTimeField(blank=True, null=True, verbose_name='preferred date')),
                ('preferred_date_from', models.DateTimeField(blank=True, null=True, verbose_name='preferred date from')),
                ('preferred_date_to', models.DateTimeField(blank=True, null=True, verbose_name='preferred date to')),
                ('location', models.TextField(blank=True, max_length=200, null=True, verbose_name='location')),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, 'Important'), (1, 'Normal')], default=0, max_length=2, verbose_name='priority')),
                ('publication_status', models.PositiveSmallIntegerField(choices=[(0, 'Published'), (1, 'Unpublished')], default=0, max_length=2, verbose_name='publication status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donation_profile', to='accounts.UserProfile', verbose_name='user')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Done')], default=0, verbose_name='progress status')),
                ('management_status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Managed on site'), (1, 'Managed on somewhere else')], default=0, null=True, verbose_name='managed on')),
                ('details', models.TextField(blank=True, max_length=500, null=True, verbose_name='details')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donation_progress', to='donations.Donation', verbose_name='donation')),
            ],
            options={
                'verbose_name': 'Donation Progress',
                'verbose_name_plural': 'Donation Progresses',
                'ordering': ['-updated_at'],
            },
        ),
    ]
