# Generated by Django 2.2.1 on 2019-05-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Important'), (1, 'Normal')], default=0, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='publication_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Published'), (1, 'Unpublished')], default=0, verbose_name='publication status'),
        ),
    ]
