# Generated by Django 2.2.1 on 2019-08-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Blood'), (1, 'Organ'), (2, 'Tissue')], default=0, verbose_name='donation type'),
        ),
    ]
