# Generated by Django 2.2.1 on 2019-08-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20190826_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationprogress',
            name='management_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'BDonar'), (1, 'Somewhere else')], null=True, verbose_name='managed on'),
        ),
    ]
