# Generated by Django 2.2.1 on 2019-05-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20190523_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Normal'), (1, 'Important')], default=0, verbose_name='priority'),
        ),
    ]
