# Generated by Django 2.2.1 on 2019-05-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_auto_20190523_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='type',
            field=models.CharField(choices=[('Blood', 'Blood'), ('Body Organs', 'Body Organs'), ('Others', 'Others')], max_length=30, verbose_name='type'),
        ),
    ]
