# Generated by Django 2.2.1 on 2019-05-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_auto_20190523_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='custom_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='custom type name'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='type',
            field=models.CharField(choices=[('Blood', 'Blood'), ('Body Organs', 'Body Organs'), ('Others', 'Others')], max_length=30, verbose_name='donation type'),
        ),
    ]
