# Generated by Django 2.2.1 on 2019-09-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_auto_20190827_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='verification'),
        ),
    ]
