# Generated by Django 2.2.1 on 2019-09-25 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_auto_20190902_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationprogress',
            name='respondent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_progress_respondent', to=settings.AUTH_USER_MODEL, verbose_name='respondent'),
        ),
    ]
