# Generated by Django 2.2.1 on 2019-05-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_auto_20190523_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='contact number'),
        ),
        migrations.AddField(
            model_name='donation',
            name='contact2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='contact number 2'),
        ),
        migrations.AddField(
            model_name='donation',
            name='contact3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='contact number 3'),
        ),
    ]
