# Generated by Django 2.2.1 on 2019-05-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_auto_20190523_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='contact',
            field=models.CharField(max_length=20, verbose_name='contact number'),
        ),
    ]
