# Generated by Django 2.2.1 on 2019-05-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_auto_20190523_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='title',
            field=models.CharField(max_length=60, verbose_name='post title'),
        ),
    ]
