# Generated by Django 2.2.1 on 2019-09-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_auto_20190930_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationprogress',
            name='respondent',
            field=models.ManyToManyField(blank=True, related_name='donation_progress_respondent', to='donations.DonationRespond', verbose_name='respondent'),
        ),
    ]
