# Generated by Django 2.2.1 on 2019-10-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_auto_20190930_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationprogress',
            name='is_pending',
            field=models.BooleanField(default=False, verbose_name='is pending'),
        ),
    ]
