# Generated by Django 2.2.1 on 2019-10-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_donationprogress_is_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrespond',
            name='is_selected',
            field=models.BooleanField(default=True, verbose_name='is selected'),
        ),
    ]
