# Generated by Django 2.2.1 on 2019-05-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_auto_20190524_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='contact',
            field=models.CharField(max_length=20, verbose_name='contact number'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='contact2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='contact number 2'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='contact3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='contact number 3'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='details',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='details'),
        ),
    ]
