# Generated by Django 2.2.1 on 2019-10-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_auto_20191005_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrespond',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='is selected'),
        ),
    ]
