# Generated by Django 2.2.1 on 2019-05-24 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_auto_20190524_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='contact',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='contact number'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='contact2',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='contact number 2'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='contact3',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='contact number 3'),
        ),
    ]
