# Generated by Django 2.2.1 on 2019-10-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_auto_20191005_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrespond',
            name='is_applied_for_selection',
            field=models.BooleanField(default=False, verbose_name='is applied for selection'),
        ),
    ]
