# Generated by Django 2.2.1 on 2019-05-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_auto_20190524_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='blood_bag',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='quantity'),
        ),
    ]
