# Generated by Django 2.2.1 on 2019-05-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0014_auto_20190526_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='blood_bag',
            field=models.PositiveIntegerField(blank=True, default=1, max_length=4, null=True, verbose_name='blood bag quantity'),
        ),
    ]
