# Generated by Django 2.2.1 on 2019-10-05 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0014_auto_20191005_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationprogress',
            name='is_pending',
        ),
    ]
