# Generated by Django 2.2.1 on 2019-05-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0016_auto_20190527_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='blood_bag',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='blood bag quantity'),
        ),
    ]
