# Generated by Django 2.2.1 on 2019-05-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0017_auto_20190527_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationprogress',
            name='progress_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Done')], null=True, verbose_name='progress status'),
        ),
    ]
