# Generated by Django 2.2.1 on 2019-05-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0018_auto_20190528_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationprogress',
            name='management_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Managed on site'), (1, 'Managed on somewhere else')], null=True, verbose_name='managed on'),
        ),
        migrations.AlterField(
            model_name='donationprogress',
            name='progress_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Done')], default=0, verbose_name='progress status'),
        ),
    ]
