# Generated by Django 2.2.1 on 2019-05-28 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0019_auto_20190528_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_profile', to='accounts.UserProfile', verbose_name='user'),
        ),
    ]
