# Generated by Django 2.2.1 on 2019-05-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0020_auto_20190528_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Offer Donation'), (1, 'Ask for Donation')], verbose_name='category'),
        ),
    ]
