# Generated by Django 2.2.1 on 2019-05-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0021_auto_20190528_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Blood'), (1, 'Body Organs'), (2, 'Others')], verbose_name='donation type'),
        ),
    ]
