# Generated by Django 2.2.1 on 2019-05-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0022_auto_20190529_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='type',
            field=models.CharField(choices=[('0', 'Blood'), ('1', 'Body Organs'), ('2', 'Others')], max_length=30, verbose_name='donation type'),
        ),
    ]
