# Generated by Django 2.2.1 on 2019-05-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0024_auto_20190529_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='preferred location'),
        ),
    ]
