# Generated by Django 2.2.1 on 2019-05-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0025_auto_20190529_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='contact',
            field=models.CharField(max_length=17, verbose_name='contact number'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='contact2',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='contact number 2'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='contact3',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='contact number 3'),
        ),
    ]
