# Generated by Django 2.2.1 on 2019-05-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0026_auto_20190530_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='details'),
        ),
    ]
