# Generated by Django 2.2.1 on 2019-06-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0027_auto_20190530_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationprogress',
            name='progress_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Completed')], default=0, verbose_name='progress status'),
        ),
    ]
