# Generated by Django 2.2.1 on 2019-06-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0028_auto_20190602_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Blood'), (1, 'Organ'), (2, 'Other')], verbose_name='donation type'),
        ),
    ]
