# Generated by Django 2.2.1 on 2019-06-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0030_auto_20190613_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='preferred location'),
        ),
    ]
