# Generated by Django 2.2.1 on 2019-06-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0032_auto_20190613_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='location',
            field=models.CharField(default='', max_length=200, verbose_name='preferred location'),
        ),
    ]
