# Generated by Django 2.2.1 on 2019-06-23 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0035_auto_20190613_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationUtil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_util', to='donations.Donation', verbose_name='donation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donation_util_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
