# Generated by Django 2.2.1 on 2019-06-23 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0036_donationutil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationutil',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Donation Util', 'verbose_name_plural': 'Donation Utils'},
        ),
    ]
