# Generated by Django 2.2.1 on 2019-06-23 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0037_auto_20190623_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationutil',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_util_user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
