# Generated by Django 2.2.1 on 2019-06-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0038_auto_20190623_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='hospital',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='hospital'),
        ),
    ]
