# Generated by Django 2.2.1 on 2019-06-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0040_auto_20190626_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('Any Blood Group', 'Any Blood Group'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=20, null=True, verbose_name='blood group'),
        ),
    ]
