# Generated by Django 2.2.1 on 2019-06-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0041_auto_20190626_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationprogress',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completion date'),
        ),
    ]
