# Generated by Django 2.2.1 on 2019-07-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0042_donationprogress_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='contact_privacy',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Public'), (1, 'Private')], default=0, verbose_name='contact privacy'),
        ),
    ]
