# Generated by Django 2.2.1 on 2019-07-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0044_donationrespond'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrespond',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='message'),
        ),
    ]
