# Generated by Django 2.2.1 on 2019-07-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0046_auto_20190706_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrespond',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='message'),
        ),
    ]
