# Generated by Django 2.2.1 on 2019-07-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0049_auto_20190706_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='custom_type',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='organ_name',
        ),
        migrations.AddField(
            model_name='donation',
            name='donate_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Living'), (1, 'Deceased')], default=0, verbose_name='donate type'),
        ),
        migrations.AddField(
            model_name='donation',
            name='organ_choice',
            field=models.CharField(blank=True, choices=[('Heart', 'Heart'), ('Kidney', 'Kidney'), ('Pancreas', 'Pancreas'), ('Lungs', 'Lungs'), ('Liver', 'Liver'), ('Intestines', 'Intestines')], max_length=100, null=True, verbose_name='organ choice'),
        ),
        migrations.AddField(
            model_name='donation',
            name='quantity',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='donation',
            name='tissue_choice',
            field=models.CharField(blank=True, choices=[('Bones', 'Bones'), ('Ligaments', 'Ligaments'), ('Tendons', 'Tendons'), ('Fascia', 'Fascia'), ('Veins', 'Veins'), ('Nerves', 'Nerves'), ('Corneas', 'Corneas'), ('Heart Valves', 'Heart Valves'), ('Skin', 'Skin')], max_length=100, null=True, verbose_name='tissue choice'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Blood'), (1, 'Organ'), (2, 'Tissue')], verbose_name='donation type'),
        ),
    ]
