# Generated by Django 2.2.1 on 2019-07-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0050_auto_20190709_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='tissue_choice',
            field=models.CharField(blank=True, choices=[('Bones', 'Bones'), ('Ligaments', 'Ligaments'), ('Tendons', 'Tendons'), ('Fascia', 'Fascia'), ('Veins', 'Veins'), ('Nerves', 'Nerves'), ('Corneas', 'Corneas'), ('Sclera', 'Sclera'), ('Heart Valves', 'Heart Valves'), ('Skin', 'Skin')], max_length=100, null=True, verbose_name='tissue choice'),
        ),
    ]
