# Generated by Django 2.2.1 on 2019-07-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0051_auto_20190709_0440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='organ_choice',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='tissue_choice',
        ),
        migrations.AddField(
            model_name='donation',
            name='organ_name',
            field=models.CharField(blank=True, choices=[('Heart', 'Heart'), ('Kidney', 'Kidney'), ('Pancreas', 'Pancreas'), ('Lungs', 'Lungs'), ('Liver', 'Liver'), ('Intestines', 'Intestines')], max_length=100, null=True, verbose_name='organ name'),
        ),
        migrations.AddField(
            model_name='donation',
            name='tissue_name',
            field=models.CharField(blank=True, choices=[('Bones', 'Bones'), ('Ligaments', 'Ligaments'), ('Tendons', 'Tendons'), ('Fascia', 'Fascia'), ('Veins', 'Veins'), ('Nerves', 'Nerves'), ('Corneas', 'Corneas'), ('Sclera', 'Sclera'), ('Heart Valves', 'Heart Valves'), ('Skin', 'Skin')], max_length=100, null=True, verbose_name='tissue name'),
        ),
    ]
