# Generated by Django 2.2.1 on 2019-07-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0052_auto_20190709_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrespond',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='is selected'),
        ),
    ]
