# Generated by Django 2.2.1 on 2019-07-24 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0053_donationrespond_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationprogress',
            name='respondent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_progress_respondent', to=settings.AUTH_USER_MODEL, verbose_name='respondent'),
        ),
    ]
