# Generated by Django 2.2.1 on 2019-07-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0054_donationprogress_respondent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationprogress',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='completion date'),
        ),
    ]
