# Generated by Django 2.2.1 on 2019-07-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0055_auto_20190724_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='is verified'),
        ),
    ]
