# Generated by Django 2.2.1 on 2019-08-02 21:30

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=100, verbose_name='institute name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('address', models.CharField(max_length=250, verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='state/province')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('contact', models.CharField(max_length=100, verbose_name='contact no.')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'DonationBank',
                'verbose_name_plural': 'DonationBanks',
                'ordering': ['-created_at'],
            },
        ),
    ]
