# Generated by Django 2.2.1 on 2019-08-23 01:42

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='campaign name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('held_date', models.DateTimeField(verbose_name='held date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='contact')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='state/province')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('details', models.TextField(blank=True, null=True, verbose_name='details/rules-regulations')),
                ('volunteer_request', models.PositiveSmallIntegerField(default=0, verbose_name='volunteer request')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_campaign', to='donationBank.DonationBank', verbose_name='bank')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-updated_at'],
            },
        ),
    ]
