# Generated by Django 2.2.1 on 2019-08-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0002_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='volunteer_request',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Allow'), (1, "Don't Allow")], default=0, verbose_name='volunteer request'),
        ),
    ]
