# Generated by Django 2.2.1 on 2019-08-07 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donationBank', '0002_bankmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_member_request', to='donationBank.DonationBank', verbose_name='bank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_member_request', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'MemberRequest',
                'verbose_name_plural': 'MemberRequests',
                'ordering': ['-created_at'],
            },
        ),
    ]
