# Generated by Django 2.2.1 on 2019-08-23 03:32

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0003_auto_20190823_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.utils.upload_campaign_image_path, verbose_name='image/banner'),
        ),
    ]
