# Generated by Django 2.2.1 on 2019-08-07 01:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0003_memberrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrequest',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
