# Generated by Django 2.2.1 on 2019-08-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0004_campaign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='contact',
            field=models.CharField(max_length=20, verbose_name='contact'),
        ),
    ]
