# Generated by Django 2.2.1 on 2019-08-07 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0004_memberrequest_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationBankSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_request', models.PositiveSmallIntegerField(default=0, verbose_name='users can send member request')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('bank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donationBank.DonationBank', verbose_name='bank')),
            ],
            options={
                'verbose_name': 'DonationBankSetting',
                'verbose_name_plural': 'DonationBankSettings',
                'ordering': ['-created_at'],
            },
        ),
    ]
