# Generated by Django 2.2.1 on 2019-08-26 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0005_auto_20190823_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_campaign', to='donationBank.Campaign', verbose_name='data source'),
        ),
    ]
