# Generated by Django 2.2.1 on 2019-08-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0005_donationbanksetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmember',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Creator'), (1, 'Maintainer')], default=1, verbose_name='member role'),
        ),
        migrations.AlterField(
            model_name='donationbanksetting',
            name='member_request',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Allow'), (1, 'Not Allow')], default=0, verbose_name='users can send member request'),
        ),
    ]
