# Generated by Django 2.2.1 on 2019-08-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0006_auto_20190807_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationbanksetting',
            name='member_request',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Allow'), (1, 'Not Allow')], default=0, verbose_name='member request'),
        ),
    ]
