# Generated by Django 2.2.1 on 2019-08-27 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0007_remove_donation_data_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='volunteer_request',
        ),
    ]
