# Generated by Django 2.2.1 on 2019-08-07 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0007_auto_20190807_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationbanksetting',
            name='bank',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_setting', to='donationBank.DonationBank', verbose_name='bank'),
        ),
    ]
