# Generated by Django 2.2.1 on 2019-09-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0009_donationbanksetting_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationbank',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='is verified'),
        ),
    ]
