# Generated by Django 2.2.1 on 2019-08-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0010_donationprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
