# Generated by Django 2.2.1 on 2019-09-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0010_donationbank_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationbank',
            name='services',
            field=models.CharField(default='Blood', max_length=100, verbose_name='services'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donationbanksetting',
            name='privacy',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Public'), (1, 'Private')], default=1, verbose_name='privacy'),
        ),
    ]
