# Generated by Django 2.2.1 on 2019-08-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0011_auto_20190814_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='contact',
            field=models.CharField(max_length=20, verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10, verbose_name='gender'),
        ),
    ]
