# Generated by Django 2.2.1 on 2019-08-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0012_auto_20190815_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='deseases',
        ),
        migrations.AddField(
            model_name='donation',
            name='diseases',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='diseases (If any)'),
        ),
    ]
