# Generated by Django 2.2.1 on 2019-09-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0012_auto_20190922_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationbank',
            name='services',
            field=models.CharField(max_length=100, verbose_name='services'),
        ),
    ]
