# Generated by Django 2.2.1 on 2019-08-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0013_auto_20190815_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='collection_date',
            field=models.DateField(verbose_name='collection date'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='expiration_date',
            field=models.DateField(verbose_name='expiration date'),
        ),
    ]
