# Generated by Django 2.2.1 on 2019-09-22 17:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0015_auto_20190922_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationbank',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Blood', 'Blood'), ('Organ', 'Organ'), ('Tissue', 'Tissue')], max_length=100, verbose_name='services'),
        ),
    ]
