# Generated by Django 2.2.1 on 2019-09-22 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0016_auto_20190922_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Blood'), (1, 'Organ'), (2, 'Tissue')], default=0, verbose_name='donation type')),
                ('blood_group', models.CharField(blank=True, choices=[('Any Blood Group', 'Any Blood Group'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=20, null=True, verbose_name='blood group')),
                ('blood_bag', models.CharField(blank=True, max_length=4, null=True, verbose_name='blood bag quantity')),
                ('organ_name', models.CharField(blank=True, choices=[('Heart', 'Heart'), ('Kidney', 'Kidney'), ('Pancreas', 'Pancreas'), ('Lungs', 'Lungs'), ('Liver', 'Liver'), ('Intestines', 'Intestines')], max_length=100, null=True, verbose_name='organ name')),
                ('tissue_name', models.CharField(blank=True, choices=[('Bones', 'Bones'), ('Ligaments', 'Ligaments'), ('Tendons', 'Tendons'), ('Fascia', 'Fascia'), ('Veins', 'Veins'), ('Nerves', 'Nerves'), ('Corneas', 'Corneas'), ('Sclera', 'Sclera'), ('Heart Valves', 'Heart Valves'), ('Skin', 'Skin')], max_length=100, null=True, verbose_name='tissue name')),
                ('quantity', models.CharField(blank=True, max_length=4, null=True, verbose_name='quantity')),
                ('details', models.TextField(blank=True, null=True, verbose_name='details')),
                ('publication_status', models.PositiveSmallIntegerField(choices=[(0, 'Published'), (1, 'Unpublished')], default=0, verbose_name='publication status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_bank_request', to='donationBank.DonationBank', verbose_name='bank')),
            ],
            options={
                'verbose_name': 'Donation Request',
                'verbose_name_plural': 'Donation Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
