# Generated by Django 2.2.1 on 2019-09-22 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0017_donationrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationrequest',
            old_name='type',
            new_name='donation_type',
        ),
    ]
