# Generated by Django 2.2.1 on 2019-09-22 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0018_auto_20190922_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationrequest',
            name='blood_bag',
        ),
    ]
