# Generated by Django 2.2.1 on 2019-09-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0020_auto_20190922_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='quantity',
            field=models.SmallIntegerField(blank=True, max_length=4, null=True, verbose_name='quantity'),
        ),
    ]
