# Generated by Django 2.2.1 on 2019-09-22 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0021_auto_20190922_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='quantity'),
        ),
    ]
