# Generated by Django 2.2.1 on 2019-09-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0022_auto_20190922_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='quantity',
            field=models.CharField(default=1, max_length=3, verbose_name='quantity'),
        ),
    ]
