# Generated by Django 2.2.1 on 2019-09-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0023_auto_20190922_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationbanksetting',
            name='member_request',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Allow'), (1, 'Not Allow')], default=1, verbose_name='member request'),
        ),
        migrations.AlterField(
            model_name='donationbanksetting',
            name='privacy',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Public'), (1, 'Private')], default=0, verbose_name='privacy'),
        ),
    ]
