# Generated by Django 2.2.1 on 2019-11-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationBank', '0025_donationrequestprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='quantity',
            field=models.CharField(blank=True, default=1, max_length=3, null=True, verbose_name='quantity'),
        ),
    ]
