# Generated by Django 2.2.1 on 2019-08-02 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_header_color', models.CharField(blank=True, max_length=100, null=True, verbose_name='logo header color')),
                ('navbar_header_color', models.CharField(blank=True, max_length=100, null=True, verbose_name='navbar header color')),
                ('sidebar_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='sidebar color')),
                ('background_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='background color')),
                ('sidebar_type', models.CharField(blank=True, default='Default', max_length=50, null=True, verbose_name='sidebar type')),
                ('scroll_to_top', models.BooleanField(default=True, verbose_name='scroll to top')),
                ('chat_with_others', models.BooleanField(default=True, verbose_name='chat with others')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_site_preference', to='accounts.UserProfile', verbose_name='user')),
            ],
            options={
                'verbose_name': 'Site Preference',
                'verbose_name_plural': 'Site Preferences',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='category')),
                ('identifier', models.CharField(blank=True, max_length=255, null=True, verbose_name='identifier')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='subject')),
                ('message', models.TextField(blank=True, max_length=1000, null=True, verbose_name='message')),
                ('is_seen', models.BooleanField(default=False, verbose_name='is seen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_receiver', to=settings.AUTH_USER_MODEL, verbose_name='receiver')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_sender', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.PositiveSmallIntegerField(default=0, verbose_name='location type')),
                ('location', models.TextField(blank=True, null=True, verbose_name='location')),
                ('hit', models.PositiveIntegerField(default=1, verbose_name='hit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_provider', to=settings.AUTH_USER_MODEL, verbose_name='provider')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['-updated_at'],
            },
        ),
    ]
