# Generated by Django 2.2.1 on 2019-05-10 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20190510_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_header_color', models.CharField(blank=True, max_length=100, null=True, verbose_name='logo header color')),
                ('navbar_header_color', models.CharField(blank=True, max_length=100, null=True, verbose_name='navbar header color')),
                ('sidebar_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='sidebar color')),
                ('background_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='background color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_site_preference', to='accounts.UserProfile', verbose_name='user')),
            ],
        ),
    ]
