# Generated by Django 2.2.1 on 2019-05-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreference',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('Default', 'Default'), ('Compact', 'Compact'), ('Overlay', 'Overlay'), ('Icon', 'Icon'), ('Static', 'Static')], max_length=50, null=True, verbose_name='sidebar type'),
        ),
    ]
