# Generated by Django 2.2.1 on 2019-05-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_sitepreference_sidebar_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepreference',
            name='sidebar_type',
            field=models.CharField(blank=True, choices=[('Default', 'Default'), ('Compact', 'Compact'), ('Overlay', 'Overlay'), ('Icon', 'Icon'), ('Static', 'Static')], default='Default', max_length=50, null=True, verbose_name='sidebar type'),
        ),
    ]
