# Generated by Django 2.2.1 on 2019-05-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_auto_20190511_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepreference',
            name='sidebar_type',
            field=models.CharField(blank=True, default='Default', max_length=50, null=True, verbose_name='sidebar type'),
        ),
    ]
