# Generated by Django 2.2.1 on 2019-05-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_auto_20190511_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreference',
            name='scroll_to_top',
            field=models.BooleanField(default=True, verbose_name='scroll to top'),
        ),
    ]
