# Generated by Django 2.2.1 on 2019-05-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_sitepreference_scroll_to_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreference',
            name='chat_with_others',
            field=models.BooleanField(default=True, verbose_name='chat with others'),
        ),
    ]
