# Generated by Django 2.2.1 on 2019-06-26 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0006_sitepreference_chat_with_others'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitepreference',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Site Preference', 'verbose_name_plural': 'Site Preferences'},
        ),
        migrations.AlterField(
            model_name='sitepreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_site_preference', to='accounts.UserProfile', verbose_name='user'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.PositiveSmallIntegerField(default=0, verbose_name='location type')),
                ('location', models.TextField(blank=True, null=True, verbose_name='location')),
                ('hit', models.PositiveIntegerField(default=0, verbose_name='hit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_provider', to=settings.AUTH_USER_MODEL, verbose_name='provider')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['-updated_at'],
            },
        ),
    ]
