# Generated by Django 2.2.1 on 2019-05-21 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_sitepreference_chat_with_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_site_preference', to='accounts.UserProfile', verbose_name='user'),
        ),
    ]
