# Generated by Django 2.2.1 on 2019-06-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_auto_20190626_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='hit',
            field=models.PositiveIntegerField(default=1, verbose_name='hit'),
        ),
    ]
