# Generated by Django 2.2.1 on 2019-07-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='identifier',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='subject'),
        ),
    ]
