# Generated by Django 2.2.1 on 2019-07-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_auto_20190724_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subject'),
        ),
    ]
